### ISSUE TITLE
Doesn't accept -0

### ISSUE THREAD

**Issue by GsHeri** [silentmatt/javascript-biginteger#23]
is this intentional?

**Comment by ashnur** [comment]
If it's possible, can you please provide a few lines of code of what you are trying to do? 
Furthermore, in javascript `-0 === +0` results in true, so there aren't too many valid reasons to deal with minus zero afaik.

**Comment by GsHeri** [comment]
hey there :)

I tried to read a fee value (coming from db, output directly to page) like this:

Amount: 235345235234534.38235341
Fees: -0.5


Idea was to split everything by the dots and calculate each side on its own (because javascript, big floats etc...)

so i grabbed the fee string and tried to generate a BigInteger from it (because, as you said.. -0 === +0 so i thought that would work)
but it didn't ;)

that's pretty much it

regards

**Comment by silentmatt** [comment]
For something like that, I would keep track of whether there's a minus sign or not, then parse the number without it, and negate the result if needed. In principle, the library could support -0, because it uses a sign-magnitude format, but maintaining the sign correctly would add a lot of complexity with no benefit for most use cases.

You might also want to consider using a decimal library like https://github.com/MikeMcl/decimal.js/ instead of building it up from an integer type. You can set the precision if you're specifically looking for fixed point decimals. There are other libraries too, but I haven't tried most of them.
